name: bilibili
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluro: ^2.0.5
  audioplayers: ^5.1.0
  dio: ^5.3.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  # fonts:
    # - family: SourceSans3
    #   fonts:
    #     - asset: assets/fonts/SourceSans3-Regular.ttf
    # - family: Pacifico
    #   fonts:
    #    - asset: assets/fonts/Pacifico-Regular.ttf
