name: myetc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluro: ^2.0.5
  audioplayers: ^5.1.0
  dio: ^5.3.3
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  http: ^1.1.0
  card_swiper: ^3.0.1
  status_bar_control: ^3.2.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  lottie: ^2.6.0
  chewie: ^1.7.1
  video_player: ^2.7.2
  web_socket_channel: ^2.4.0
  path_provider: ^2.1.1
  getwidget:
    git:
      url: https://github.com/ionicfirebaseapp/getwidget.git
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.5.0
  webview_flutter: ^4.4.1
  uuid: ^4.1.0
  flutter_line_sdk: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    # fonts:
    # - family: SourceSans3
    #   fonts:
    #     - asset: assets/fonts/SourceSans3-Regular.ttf
    # - family: Pacifico
    #   fonts:
    #    - asset: assets/fonts/Pacifico-Regular.ttf
